name: Build and deploy docs

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
            submodules: true
      - uses: actions/setup-python@v1
      - name: Install GSL
        run: sudo apt install libgsl0-dev
      - name: Install python-deps
        run: python -m pip install -r requirements/docs.txt
      - name: Build C module
        run: make cmodule
      - name: Build Docs
        run: make -C docs
